# scraper/rss_to_csv.py
import csv, feedparser
FEEDS = [
    "https://semiengineering.com/tag/rss/",
    "https://spectrum.ieee.org/feeds/topic/semiconductors.rss",
    "https://nvidianews.nvidia.com/rss",
]
rows = []
for url in FEEDS:
    d = feedparser.parse(url)
    src = d.feed.get("title","")
    for e in d.entries:
        rows.append({
            "title": e.get("title","").strip(),
            "url": e.get("link",""),
            "published": e.get("published",""),
            "source": src
        })
with open("data/news.csv","w",newline="",encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=["title","url","published","source"])
    w.writeheader(); w.writerows(rows)
print(f"OK {len(rows)}")
